# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wfs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(388, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("wfs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_import = QtWidgets.QPushButton(self.widget)
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_2.addWidget(self.btn_import, 0, 0, 1, 1)
        self.btn_export = QtWidgets.QPushButton(self.widget)
        self.btn_export.setObjectName("btn_export")
        self.gridLayout_2.addWidget(self.btn_export, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 5)
        self.ckb_filter = QtWidgets.QCheckBox(self.widget)
        self.ckb_filter.setObjectName("ckb_filter")
        self.gridLayout_2.addWidget(self.ckb_filter, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.ckb_case_sensitive = QtWidgets.QCheckBox(self.widget)
        self.ckb_case_sensitive.setChecked(True)
        self.ckb_case_sensitive.setTristate(False)
        self.ckb_case_sensitive.setObjectName("ckb_case_sensitive")
        self.gridLayout_2.addWidget(self.ckb_case_sensitive, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Word Frequency Statistics"))
        self.btn_import.setText(_translate("Form", "Import"))
        self.btn_export.setText(_translate("Form", "Export"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Word"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Frequency"))
        self.ckb_filter.setText(_translate("Form", "Filter"))
        self.ckb_case_sensitive.setText(_translate("Form", "Case Sensitive"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
